services:
  frontend:
    container_name: terra-frontend
    image: tipex360/terrafirma-frontend:0.6
    ports:
      - "3000:3000"
    networks:
      - terra-net
    hostname: frontend
    env_file: packages/frontend/.env.local
    restart: always

  rest:
    container_name: terra-rest
    image: tipex360/terrafirma-rest:0.1
    networks:
      - terra-net
    hostname: rest
    env_file: packages/rest/.env
    restart: always
    volumes:
      - ./logs:/log

  worker:
    container_name: terra-worker
    image: tipex360/terrafirma-worker:0.1
    hostname: worker
    env_file: packages/worker/.env
    restart: always
    volumes:
      - ./logs:/log
    networks:
      - terra-net

networks:
  terra-net:
    name: terra-net
    external: false
